### ISSUE TITLE
Be able to supply port to Dnsruby::DNS

### ISSUE THREAD

**Issue by dentarg** [alexdalitz/dnsruby#100]
With `resolv` I can do this:

``` ruby
Resolv::DNS.new(nameserver_port: [["8.8.8.8", 53], ["8.8.4.4", 53]])
```

With `dnsruby` I can do this

``` ruby
Dnsruby::Resolver.new(nameserver: ["8.8.8.8", "8.8.4.4"], port: 53)
```

but `Dnsruby::Resolver` is much more low-level than what I want. I want to use `Dnsruby::DNS` which has all the nice methods like `getaddress` and `getname`.

The use-case I have for this is that, in my integration test, I actually start [NSD](http://www.nlnetlabs.nl/projects/nsd/) on a custom port and make real queries. So my tests passes that port on to my dns client class in the application, in the test setup. In production I default to the standard port.

What do you think about this?

Is it an relatively easy change so I could try make a pull request for it?

**Comment by alexdalitz** [comment]
Sorry - why can’t you just use Dnsruby::DNS?

**Comment by dentarg** [comment]
@alexdalitz ok, then I don't understand how to configure `Dnsruby::DNS` with a custom port, do you have an example?

**Comment by dentarg** [comment]
I tried this, but as you see `@port` is still 53, not 5300

```ruby
[10] pry(main)> client = Dnsruby::DNS.new(nameserver: ["127.0.0.1"], port: 5300)
=> #<Dnsruby::DNS:0x007faa74dafa18
 @config=Config - nameservers : 127.0.0.1,  domain : empty, search : live.lkp.primelabs.se, lkp.primelabs.se,  ndots : 1,
 @do_caching=true,
 @resolver=
  #<Dnsruby::Resolver:0x007faa74db40e0
   @config=Config - nameservers : 127.0.0.1,  domain : empty, search : live.lkp.primelabs.se, lkp.primelabs.se,  ndots : 1,
   @configured=false,
   @dnssec=true,
   @do_caching=true,
   @do_validation=false,
   @ignore_truncation=false,
   @no_tcp=false,
   @packet_timeout=5,
   @port=53,
   @query_timeout=0,
   @recurse=true,
   @resolver_ruby=nil,
   @retry_delay=5,
   @retry_times=1,
   @single_res_mutex=#<Mutex:0x007faa74db4068>,
   @single_resolvers=[],
   @src_address=nil,
   @src_address6=nil,
   @src_port=[0],
   @tcp_pipelining=false,
   @tcp_pipelining_max_queries=5,
   @tsig=nil,
   @udp_size=4096,
   @use_tcp=false>>

[11] pry(main)> client.getaddress("starkast.net")
Dnsruby::OtherResolvError: recvfrom failed from 127.0.0.1; Connection refused - recvfrom(2)
from /Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/DNS.rb:298:in `send_query'
```

**Comment by alexdalitz** [comment]
Hi - 

Sorry about the delay.

The aim is for dnsruby to replicate the resolv interface, so this feature should be made available.

I'm afraid I've been extremely pushed for time recently (which is likely to continue for the next week or so), but I will make sure that this is working by the next release.

Thanks, and apologies,


Alex.

**Comment by dentarg** [comment]
@alexdalitz no worries, just let me know if I could help (but it sounds like you want to do it yourself, you might have something in mind how it should be done?)

**Comment by alexdalitz** [comment]
Sorry just come back to this, many apologies. 

If you had the time and inclination to look, I'd be delighted to accept patches!

I'm afraid I don't know when I'm going to be able to get the time to look at this, although I do hope to do so, and will leave the issue open.

Thanks, and apologies,


Alex.

**Comment by dentarg** [comment]
no worries, we went another route with our project, so I'm afraid I wont be looking into writing any patch at the moment...

but dnsruby seems like an interesting project, so if my spare time would allow, I might take a stab it, some time in the future :) don't want to make any promises though

**Comment by alexdalitz** [comment]
Apologies for the delay.

You can now do  (as per your example) : `client = Dnsruby::DNS.new(nameserver: ["127.0.0.1"], port: 5300)`

Thanks!
