### ISSUE TITLE
README links to non-existent blog posts

### ISSUE THREAD

**Issue by mbunkus** [alexdalitz/dnsruby#101]
The README links to two posts on blog.nominet.org.uk in the section "usage help", and neither of those pages exist.

**Comment by keithrbennett** [comment]
@alexdalitz , if you don't plan to reinstate or relocate those links, I can just remove that section from the README if you like (in a pull request).

**Comment by alexdalitz** [comment]
Oops sorry they must have been removed. I'll add the contents to the dnsruby help files, but I won't be near a computer for another couple of weeks I'm afraid...

**Comment by alexdalitz** [comment]
...just trying to look at this - sorry for the delay. I'm waiting for the computer with the files on to dry out before I can switch it on again to retrieve them... :-/

I will make sure these files are added before the next release - sorry about the length of time this is taking...

**Comment by turboladen** [comment]
I just ran into this too...

**Comment by alexdalitz** [comment]
Ok thanks for the prod. I've got the content, and will try to massage it into something soon.

**Comment by alexdalitz** [comment]
OK I've now fixed the README, and added the content to the github wiki. I hope this helps!

**Comment by turboladen** [comment]
🎉

**Comment by keithrbennett** [comment]
I've formatted it with headings, code blocks, etc.
