### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by dansteele** [alexdalitz/dnsruby#103]
Props to @mlocher at Codeship for working this out!

```bash
$ gem install dnsruby
Fetching: dnsruby-1.59.2.gem (100%)
Installing dnsruby...
  For issues and source code: https://github.com/alexdalitz/dnsruby
  For general discussion (please tell us how you use dnsruby): https://groups.google.com/forum/#!forum/dnsruby
Successfully installed dnsruby-1.59.2
1 gem installed
```
even though https://rubygems.org/gems/dnsruby shows that 1.59.3 is available since May 25.

When I try to install that version explicitly I get an error message

```bash
$ gem install dnsruby -v 1.59.3
ERROR:  Could not find a valid gem 'dnsruby' (= 1.59.3) in any repository
ERROR:  Possible alternatives: Dnsruby
```

**Comment by alexdalitz** [comment]
Oh dear, sorry.

Nowhere near a computer just now but will check soon.

Thanks,

Alex.

**Comment by alexdalitz** [comment]
I've just tried this, and I don't get this issue. The commands you list all work fine for me. Is this still an issue for you?

**Comment by mlocher** [comment]
Running the installation command now installs version 1.59.3

```bash
$ gem install dnsruby
Fetching: dnsruby-1.59.3.gem (100%)
Installing dnsruby...
  For issues and source code: https://github.com/alexdalitz/dnsruby
  For general discussion (please tell us how you use dnsruby): https://groups.google.com/forum/#!forum/dnsruby
Successfully installed dnsruby-1.59.3
1 gem installed
```

Maybe this was related to Rubygems already having the new version (`1.59.3`) in their DB, but the files not being synced yet?

**Comment by alexdalitz** [comment]
Great! :-)  I'll close this issue now, but feel free to re-open it if need be...

Thanks!
