### ISSUE TITLE
Can't delete record while specifying rdata

### ISSUE THREAD

**Issue by seandilda** [alexdalitz/dnsruby#104]
If you specify rdata in an update request, the formatted packet does not include the specified rdata.

It looks like this may be caused by the fix for #102, since delete requests and must be absent prereqs both have a class of NONE

**Comment by seandilda** [comment]
#105 is a possible fix for this.

**Comment by alexdalitz** [comment]
Thanks for that - I'm a little short of time this morning but I'll try to inspect this PR and (hopefully) merge later this evening.
