### ISSUE TITLE
`create': cannot interpret as DNS name: nil (ArgumentError)

### ISSUE THREAD

**Issue by KINGSABRI** [alexdalitz/dnsruby#110]
Hi, I'm trying to update dns server with MX record, am i missing something?

```ruby
require 'dnsruby'

new_ip     = '172.16.16.1'
domain     = 'vulnerable.zone'
new_domain = 'mx.vulnerable.zone'
dns_server = '172.16.16.134'

res    = Dnsruby::Resolver.new({:nameserver => dns_server})
update = Dnsruby::Update.new(domain)

#=> Add
update.present(domain)
update.add(dns_server, Dnsruby::Types.MX, 10, new_domain)

begin
  reply = res.send_message(update)
  puts "Update succeeded"
rescue Exception => e
  p "Update failed: #{e.backtrace}"
end
```

Getting an error
```
/var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/name.rb:60:in `create': cannot interpret as DNS name: nil (ArgumentError)
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/MX.rb:42:in `from_string'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:113:in `initialize'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:282:in `new'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:282:in `_get_subclass'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:245:in `new_from_string'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:402:in `create'
        from /var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/update.rb:238:in `add'
        from dns_mx_update.rb:18:in `<main>'
```

**Comment by alexdalitz** [comment]
try :  

update.add(dns_server, Dnsruby::Types::MX, 10, new_domain)

Not quite sure why your version didn't work, but I'll look into it - in the mean time, you can use the above.

HTH

**Comment by KINGSABRI** [comment]
Thanks for reply, 
I'm getting

```
Query timed out
/var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:257:in `send_message'
```

**Comment by alexdalitz** [comment]
Yes, that server appears to reply to neither DNS nor ping packets.

**Comment by KINGSABRI** [comment]
I can't understand why this is happening, even wireshark says `format error`
```
Dynamic update response 0x35e1 Format error SOA vulnerable.zone ANY OPT
```

I tried to use `nsupdate` command and it works just perfect 

```
$ nsupdate
> server  172.16.16.128
> update add vulnerable.zone 86400 MX 10 mx.vulnerable.zone
> send
```

My code 

```ruby
#!/usr/bin/env ruby
#
# KING SABRI | @KINGSABRI
#
require 'dnsruby'

attaker_ip = '172.16.16.1'
domain     = 'vulnerable.zone'
attacker_domain = 'mx.vulnerable.zone'
dns_server = '172.16.16.128'

res = Dnsruby::Resolver.new({:nameserver => dns_server})
update = Dnsruby::Update.new(domain)

#=> Add
update.present(domain) # MX only use 'present' during "ADD" not 'absent' 
update.add(domain, Dnsruby::Types::MX, 10, attacker_domain)


begin
  reply = res.send_message(update)
  puts "Update succeeded"
rescue Exception => e
  puts e
  puts e.backtrace
end

```

The error is
```
Query timed out
/var/lib/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:257:in `send_message'
dns_mx_update.rb:27:in `<main>'
```

**Comment by alexdalitz** [comment]
I just get timeouts on both nsupdate and the dnsruby. I think it is safe to mark this issue as closed, but please let me know if I'm wrong on this.

**Comment by keithrbennett** [comment]
The bug originally reported is still a bug, though, right? If so, I think it's better to leave the issue open.

I traced through the code and found that in the example posted by @KINGSABRI `M.from_string()` (see code below) is passed `'mx.vulnerable.zone'`;

```
      def from_string(input) #:nodoc: all
        if (input.length > 0)
          names = input.split(" ")
          @preference = names[0].to_i
          # !!! SEE LINE BELOW: !!!
          @exchange = Name.create(names[1])
        end
      end
```

`names[1]` resolves to `nil`, and `nil` is passed to `Name.create()`.  Inside that method `nil` is considered an invalid input and an `ArgumentError` is raised:

```
    def self.create(arg)
      case arg
      when Name
        return Name.new(arg.labels, arg.absolute?)
      when String
        #         arg.gsub!(/\.$/o, "")
        if (arg==".")
          return Name.new([],true)
        end
        if (arg=="")
          return Name.new([],false)
        end
        return Name.new(split_escaped(arg), /\.\z/ =~ arg ? true : false)
        #         return Name.new(Label.split(arg), /\.\z/ =~ arg ? true : false)
      when Array
        return Name.new(arg, /\.\z/ =~ (arg.last ? ((arg.last.kind_of?String)?arg.last : arg.last.string) : arg.last) ? true : false)
      else
        # !!! SEE LINE BELOW: !!!
        raise ArgumentError.new("cannot interpret as DNS name: #{arg.inspect}")
      end
    end
```

If the example argument to from string does not have have a second value (`names[1]`) then it seems odd that `Name.create` would consider this an error condition.

Should this nil input be treated the same as the empty string?

**Comment by alexdalitz** [comment]
So the problem there is that the MX preference has been omitted. Or rather, it looks like the TTL has been omitted (unless the TTL is 10, but 10 looks more like an MX preference to me).

Perhaps you should try : 

update.add(domain, Dnsruby::Types::MX, 86400, 10, attacker_domain)

**Comment by alexdalitz** [comment]
(Note that it's also possible to construct the RR, then call update(rr) rather than the individual RR parameters)

**Comment by keithrbennett** [comment]
I'm not knowledgeable about the DNS going on here, but I still think that the original issue needs to be addressed, even it's only by changing the comment in `MX.from_string` with the example argument to be something that would not result in an error being raised.

Even if the OP solves the problem by implementing a workaround, others coming to this code might see the example, expect it to work, and then be confused when it doesn't.

**Comment by alexdalitz** [comment]
> I'm not knowledgeable about the DNS going on here, but I still think that the original issue needs to be addressed, even it's only by changing the comment in MX.from_string with the example argument to be something that would not result in an error being raised.
> 
Sorry - which example in which comment? Happy to change it, but can’t find it...

**Comment by keithrbennett** [comment]
Alex, very sorry, there was no example in the source code.  I had been using RubyMine as a debugger, and it added `input: "mx.vulnerable.zone"` at the end of the `from_string` method definition in such a way that it appeared to be part of the nodoc comment:

      def from_string(input) #:nodoc: all input: "mx.vulnerable.zone"

I am new to RubyMine debugging and did not realize that it was the debugger putting that value there.

That said, I think there is room for improvement in that method:

```
      def from_string(input) #:nodoc: all
        if (input.length > 0)
          names = input.split(" ")
          @preference = names[0].to_i
          @exchange = Name.create(names[1])
        end
      end
```

Maybe we should change the input length test to fail (and therefore bypass the body of the `if` clause) if there is 1 but not 2 tokens?  If not, then raise a descriptive error if `exchange` is missing?

**Comment by alexdalitz** [comment]
OK - how about 8c57341 ?

Thanks!

**Comment by keithrbennett** [comment]
Great, thank you!

**Comment by KINGSABRI** [comment]
Hello guys @alexdalitz @keithrbennett 
Thanks for taking time on this issue I'm still facing issues 
I've started with adding an A record for the new mx record then I added the new mx record as follows

```ruby
require 'dnsruby'

attacker_ip = '192.168.100.10'
attacker_domain = 'mx.vulnerable.zone'
domain     = 'vulnerable.zone'
dns_server = '192.168.100.17'

res = Dnsruby::Resolver.new({:nameservers => [dns_server]})
update = Dnsruby::Update.new(domain)

update.absent(attacker_domain, 'A')
update.add(attacker_domain, 'A', 86400, attacker_ip)
reply = res.send_message(update)
```

Then 

```ruby
require 'dnsruby'

attacker_ip = '192.168.100.10'
attacker_domain = 'mx.vulnerable.zone'
domain     = 'vulnerable.zone'
dns_server = '192.168.100.17'

res = Dnsruby::Resolver.new({:nameservers => [dns_server]})
update = Dnsruby::Update.new(domain)

update.present(attacker_domain)
update.add(domain, Dnsruby::Types::MX, 86400, 10, attacker_domain)
reply = res.send_message(update)
```

Getting 

```
Dnsruby::FormErr
/var/lib/gems/2.4.0/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:257:in `send_message'
```
I'm really confused at this point, any complete working example around? 
I think [docs](http://www.rubydoc.info/gems/dnsruby/1.60.1/Dnsruby/Update) need to be updated as well

**Comment by alexdalitz** [comment]
I'm very sorry this is still a pain for you.

Could you please try -

mx = Dnsruby::RR.create("#{domain) 86400 IN MX 10 #{attacker_domain}")
update.add(mx)

I suspect there is something slightly broken with the update RR creation from string, and this approach (creating the RR directly then adding it to the update) should hopefully work, thus showing that I need to the the update RR creation from string.

Please let me know how it goes.

Thanks!

**Comment by KINGSABRI** [comment]
@alexdalitz appreciate your response 
and YES it works!

**Comment by keithrbennett** [comment]
@KINGSABRI @alexdalitz In case this helps, I wrote a test file that shows the difference in the string representations of the 2 update objects created in the 2 different ways. It's at https://github.com/keithrbennett/dnsruby/blob/issue_110_debugging/test/tc_issue_110.rb. Output is at the bottom of the file. (If you run this you'll need to gem install diffy.)

**Comment by keithrbennett** [comment]
@KINGSABRI @alexdalitz I added a couple of scenarios to this test file.  It looks like omitting the 10 resulted in an improvement.  Also, I looked to see if using the string 'MX' instead of the type object would help, but that was even worse. 

 I made it easy to try your own argument list by just adding a call to `do_test`.

The diffy output is helpful but there is more detail in the assertion failure message.

**Comment by alexdalitz** [comment]
@KINGSABRI  : thanks for letting me know. Again, sorry that the update doesn't parse the RR correctly just now - however, you should be able to do whatever you need to by constructing the RR before passing it to the update.
I will try to find some time to fix the update parsing soon, but hopefully this will no longer hold you back.
@keithrbennett  : yes, the parsing is b0rked, and the MX type number of 15 is being added to the rdata :(   I'll fix this soon - thanks for your help

**Comment by KINGSABRI** [comment]
@alexdalitz Thanks Alex, 
I was trying to write a module for metasploit to demonstrate who dangerous leaving DNS update for any.
At the same time, metasploit guys were discussing the best gem for DNS and I believe dnsruby is the most mature gem in regard. 

Appreciate your effort for keeping this gem available and maintained.

**Comment by alexdalitz** [comment]
Sorry about the delay in answering this.
I _think_ we're just not using it right. The docs say :
` update.add(name, type, ttl, rdata)`
So I think you need to call it like this :
`update.add(domain, Dnsruby::Types::MX, 86400, "10 attacker_domain")`

Thanks!
