### ISSUE TITLE
Calls to Celluloid.boot do not have corresponding calls to Celluloid.shutdown

### ISSUE THREAD

**Issue by keithrbennett** [alexdalitz/dnsruby#122]
As per @phoet in a comment at http://stackoverflow.com/questions/42597466/ruby-method-call-made-to-wrong-top-level-module-class/42617574#42617574:

"there are two Celluloid.boot but no Celluloid.shutdown calls in the test-suite."

**Comment by alexdalitz** [comment]
This is now fixed.
