### ISSUE TITLE
Any plans to release 1.61.0?

### ISSUE THREAD

**Issue by dalibor** [alexdalitz/dnsruby#128]
To include the Ruby 2.4 Fixnum deprecation warning patch [#116](https://github.com/alexdalitz/dnsruby/pull/116). Thanks!

**Comment by alexdalitz** [comment]
Yes! 

I have lots of patches to attend to, but I've been hiking and canoeing in southern France for the last fortnight. 

I plan to make a new release on Monday.

Thanks!

Alex.

**Comment by dalibor** [comment]
Awesome, thank you! And enjoy! :)

**Comment by evaryont** [comment]
Any chance the new version could include #126 and #125?

**Comment by alexdalitz** [comment]
Yes! :-)

I've included those, and have just now released dnsruby v1.60.1 - please let me know of any issues.

Thanks!


Alex.

**Comment by dalibor** [comment]
Thanks Alex! No bugs this side.
