### ISSUE TITLE
Dnsruby::DecodeError on ANY query.

### ISSUE THREAD

**Issue by jots** [alexdalitz/dnsruby#132]
Am I doing ANY query wrong?

```ruby
require "dnsruby"
include Dnsruby
@resolver = Dnsruby::Resolver.new({:nameserver => "8.8.8.8"})
m = Message.new("google.com", Types.ANY)
pp @resolver.send_message(m)
```
results in:
./t1.rb 
/home/joe/projects/rubydns-getter/vendor/ruby/2.1.0/gems/dnsruby-1.60.1/lib/dnsruby/message/decoder.rb:32:in `assert_buffer_position_valid': requested position of 258 must be between 0 and buffer size (165). (Dnsruby::DecodeError)

Just noticed that: `m = Message.new("yahoo.com", Types.ANY)`  works.  so something about querying info about google.com.

**Comment by alexdalitz** [comment]
I think the problem is the CAA record at google.com. For some reason, dnsruby doesn't like it. I will investigate this and try to get a fix out soon.
Thanks for the report, and sorry for the hassle.

**Comment by alexdalitz** [comment]
I've pushed a fix for this to master. Could you please check it out and let me know if it works?

**Comment by jots** [comment]
it works!  Thank you!
