### ISSUE TITLE
resolve lots of dependent records in parallel.

### ISSUE THREAD

**Issue by jots** [alexdalitz/dnsruby#133]
I have about 100K names I need to resolve on a regular basis.

I have used your example mresolve to resolve the names which
works great.  But I'd like to get more data for each name,
for instance, would like:
* A record (with is_cname? flagged)
    * PTR records for each IP returned.
* NS records
  * A records for each NS
    * PTR record for each A above.
* MX records
  * A record for each exchange above
    * PTR record for each A record above.
* TXT records.

Trying to figure out the best way to do this
efficiently, i.e. run async when dependent records
are retrieved and maintain a Queue of $x domains
being processed

Has anyone implemented such a thing?
Also, is it best to use Recursor or Resolver for such a thing?

**Comment by alexdalitz** [comment]
> On 28 Jun 2017, at 23:18, jots <notifications@github.com> wrote:
> 
> I have about 100K names I need to resolve on a regular basis.
> 
> I have used your example mresolve to resolve the names which
> works great. But I'd like to get more data for each name,
> for instance, would like:
> 
> A record (with is_cname? flagged)
> PTR records for each IP returned.
> NS records
> A records for each NS
> PTR record for each A above.
> MX records
> A record for each exchange above
> PTR record for each A record above.
> TXT records.
> Trying to figure out the best way to do this
> efficiently, i.e. run async when dependent records
> are retrieved and maintain a Queue of $x domains
> being processed
> 

Yes, I would recommend running an async loop, keeping some number (1000?) of open requests and the rest queued up.

> Has anyone implemented such a thing?
> 
Yes :-)   It works just fine.
> Also, is it best to use Recursor or Resolver for such a thing?
> 
It depends on your use case. If you have a need to run your own recursion from the root, then use Recursor. If you’re just interested in having the queries resolved, then use Resolver, and make use of the global DNS cache.

HTH,


Alex.

**Comment by jots** [comment]
Thank you.  I think I have it working with `@resolver.send_async`  however if I run the same query multiple times against same @resolver instance, it seems to take around the same amount of time even though`@resolver.do_caching` is set to true.  Not sure why that is.

I didn't see how to use Recursor in async manner like Resolver allows.

**Comment by alexdalitz** [comment]
No, the Recursor does not have an async interface.

With respect to caching - it’s also possible to set caching on a message-by-message basis, and there are also some “raw” send queries which explicitly bypass the caching mechanism.

There is also a cache limit, which you can configure - perhaps the original message has been pushed out of the cache by other messages?

**Comment by alexdalitz** [comment]
Is this still an issue?

**Comment by jots** [comment]
@resolver.send_async is doing the trick.  thank you very much.
