### ISSUE TITLE
DNSSEC not working

### ISSUE THREAD

**Issue by pzb** [alexdalitz/dnsruby#136]
It seems DNSSEC checking is not working.  Using the example `digroot.rb` script, the answer is always coming back with `@security_level=INSECURE`, regardless of the name being looked up.

Example:
`ruby digroot.rb www.pir.org.`

Is is expected that this should show something other than INSECURE?

**Comment by alexdalitz** [comment]
Yes! 

I'll check this out later - I suspect I know the problem.

Thanks,

Alex.

**Comment by alexdalitz** [comment]
So I switched validation and dnssec off by default a couple of releases ago. Sadly, I forgot to update the validator to ensure that dnssec was set on the recursor and resolver used by the validator. I've now added this to my local system, and get SECURE results for your query. I'm sorry for the omission.

I need to get my children ready for school now, and am a little busy this morning - however, I'll try to get this fix fully tested and out over the next few hours.

If you need this fix in a release, please let me know, and I'll try to make a new release today as well.

**Comment by alexdalitz** [comment]
OK - I've pushed this to master now. Could you please let me know if you have any issues or concerns? As above, I'm happy to push this to a new release if it helps - just let me know.

Thanks!
