### ISSUE TITLE
JRuby 9000: deprecation warning "... interpreted as binary operator"

### ISSUE THREAD

**Issue by kevinmtrowbridge** [alexdalitz/dnsruby#137]
Thank you for your gem.

We are getting this deprecation warning with JRuby 9.1.12:

```
.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/dnsruby-1.60.2/lib/dnsruby/message/header.rb:215: warning: `+' after local variable or literal is interpreted as binary operator
```

It's not urgent, or important, but it is noisy in our logs.  I didn't find any reference to this, so I thought I would file it.

Thanks again, your gem is useful for us!
KT

**Comment by alexdalitz** [comment]
Sorry to be noising up your logs!

I hope I've fixed this issue - could you please try running on master and let me know if it fixes it for you?

**Comment by alexdalitz** [comment]
I'm going to close this as I believe it to be fixed and have had no response. Please feel free to reopen this issue if it is not working for you. I will probably make a release over the next few days, which should help if you're reluctant to run off master to test...
