### ISSUE TITLE
TypeError: no implicit conversion of nil into Array on Dnsruby::DNS#each_resource

### ISSUE THREAD

**Issue by justillusion** [alexdalitz/dnsruby#138]
I've got TypeError when call Dnsruby::DNS#each_resource
for example when i try: 
```
res = Dnsruby::DNS.new
res.each_resource('gmail.com','MX'){|rr| puts rr}
```
i've got
```
TypeError: no implicit conversion of nil into Array
	from /usr/local/bundle/gems/dnsruby-1.60.2/lib/dnsruby/config.rb:437:in `+'
	from /usr/local/bundle/gems/dnsruby-1.60.2/lib/dnsruby/config.rb:437:in `generate_candidates'
	from /usr/local/bundle/gems/dnsruby-1.60.2/lib/dnsruby/DNS.rb:281:in `send_query'
	from /usr/local/bundle/gems/dnsruby-1.60.2/lib/dnsruby/DNS.rb:231:in `each_resource'
	from (irb):42
```
it running from kubernetes container. 
res.config is
```
Config - nameservers : 10.96.0.10,  domain : empty, search : default.svc.cluster.local, svc.cluster.local, cluster.local,  ndots : 5
```

but when i run this code from local machine it works fine.

**Comment by alexdalitz** [comment]
It seems like a slightly strange config.

However, I've pushed a commit which should fix this issue. Can you please try master and let me know if it helps?

**Comment by alexdalitz** [comment]
I'm going to close this as I believe it to be fixed and have had no response. Please feel free to reopen this issue if it is not working for you. I will probably make a release over the next few days, which should help if you're reluctant to run off master to test...
