### ISSUE TITLE
CDNSKEY CDS and URI records not supported

### ISSUE THREAD

**Issue by Kilobyte22** [alexdalitz/dnsruby#139]
I just discovered that the following record types are not supported:
CDNSKEY and CDS as defined in RFC7344
URI as defined in RFC7553

Furthermore when reading a TSIG response from a zone file which has been created using `dig -y ...`, the `<keyname>.	0	ANY	TSIG	hmac-sha256. 1518478325 300 32 <tsig_data> 41534 NOERROR 0` RR emitted by dig causes a parse error.

**Comment by alexdalitz** [comment]
Hi - 

thanks for the report!

I'm sorry that some newer RR types are not yet explicitly supported. Of course, you can still use these types in dnsruby (RFC 3597 unknown types), but there are no explicit facilities to handle them.

I'm not sure when I'll next get time to look at these, I'm afraid. Of course, I'm always open to pull requests! ;-)

Regarding the TSIG error - could you please send more details on this?

Thanks,


Alex.

**Comment by alexdalitz** [comment]
Sorry for the delay.
I've now implemented the URI, CDS and CDNSKEY records. Please let me know of any problems.
