### ISSUE TITLE
Dnsruby::DNS always throws Dnsruby::NXDomain when search is in /etc/resolv.conf

### ISSUE THREAD

**Issue by mreinsch** [alexdalitz/dnsruby#140]
Scenario:

In /etc/resolv.conf:
```
nameserver 100.64.0.10
search test.svc.cluster.local svc.cluster.local cluster.local us-west-1.compute.internal
options ndots:5
```

When doing `Dnsruby::DNS.new.send_query('uue.org')`, dnsruby will lookup `uue.org.test.svc.cluster.local.`, `uue.org.svc.cluster.local.`, `uue.org.svc.cluster.local.`, `uue.org.cluster.local.` and `uue.org.us-west-1.compute.internal.`, but **NOT** `uue.org.`. 

This works contrary to any other tools out there. The 'blank' domain without the search list applied should also be looked up so dnsruby behaves like any other tool doing DNS lookups, like `ping uue.org` just resolves fine for instance.

**Comment by alexdalitz** [comment]
I suspect that ping is guessing that you might have meant an absolute name, rather than a relative one, and is trying that first.

If you want the absolute name resolved, then why not used the absolute name? 

>  Dnsruby::DNS.new.send_query(‘uue.org.')
> 
Thanks,


Alex.

**Comment by mreinsch** [comment]
@alexdalitz well, yes, then I (as the application developer) have to guess that a user probably entered the full domain and that they most likely weren't aware of the system's configuration done by kubernetes and didn't care about the internal domains.

Anyway, the current behaviour has caused me a lot of frustrations and broke some part of our system because it's not obvious at all that on every other system a lookup for `uue.org` (without the last `.`) does work just fine. Just when doing lookups on production it fails because kubernetes sets up docker containers with the search configured.

**Comment by alexdalitz** [comment]
OK.

I’m not averse to doing this. I just worry that a change in behaviour might affect somebody else’s application…

If nobody else raises any objections, then I guess I could add it in.

I have to confess that I’ve never really got on with ndots...

Thanks,


Alex.

**Comment by keithrbennett** [comment]
Not to cause anyone more work, but if this would change existing behavior,
might we make it an option somehow so that we continue to default to the
existing behavior?

Such as an alternate method with a different name, or maybe a setting that
is changed on the DNS instance?

**Comment by alexdalitz** [comment]
I've now made this change. Sorry for the delay...
