### ISSUE TITLE
Dnsruby::NXDomain error when fetching TXT records of some domains, while MX records return without error

### ISSUE THREAD

**Issue by macmartine** [alexdalitz/dnsruby#143]
How come with certain domains, I can fetch MX records just fine, but fetching TXT records I get a 'Dnsruby::NXDomain' error?

Example:

This throws a Dnsruby::NXDomain error:
```
DNS.new.getresources("kimcorealty.com", Types.TXT)
```

This works perfectly:
```
DNS.new.getresources("kimcorealty.com", Types.MX)
```

Thanks in advance

**Comment by alexdalitz** [comment]
I don't get this - see below....

require 'dnsruby'
include Dnsruby

puts DNS.new.getresources("kimcorealty.com", Types.MX)

puts DNS.new.getresources("kimcorealty.com", Types.TXT)


Outputs : 





kimcorealty.com.	1693	IN	MX	100 mxa-00297101.gslb.pphosted.com.
kimcorealty.com.	1693	IN	MX	100 mxb-00297101.gslb.pphosted.com.
kimcorealty.com.	3496	IN	TXT	"RcXQDnUbj3Sjm2Y+UUbuTkdDUwitxBDRBL7rTYHvFCkylMYMYbAamGTkooxpxJwyVeoNUQZFjf6Mn9bZtt2qkg=="
kimcorealty.com.	3496	IN	TXT	"MS=ms98433547"
kimcorealty.com.	3496	IN	TXT	"docusign=69340a61-0fcc-46b8-b7a9-2d49a40007c3"
kimcorealty.com.	3496	IN	TXT	"atlassian-domain-verification=vA/K8uyQPRi6pNbTDb5/Hu/yk900zY28QlEtwyrwRs8bKY/N7UG27xsGA8eLjS1V"
kimcorealty.com.	3496	IN	TXT	"v=spf1 ip4:167.206.63.136 ip4:64.238.213.254 ip4:66.77.249.235 ip4:66.77.249.236 ip4:216.203.55.53 ip4:216.203.55.54 ip4:209.114.43.188 include:spf.protection.outlook.com include:spf-00297101.pphosted.com ~all"
