### ISSUE TITLE
bogus invalid key issue (patch included)

### ISSUE THREAD

**Issue by ediazfer** [alexdalitz/dnsruby#144]
ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

The .e and .n fields/methods do not exist anymore in OpenSSL::PKey::RSA

    This triggers a bogus invalid key error when the code is used (hiding the true Exception about the
    method not being found)
    This tiny patch calls the setter.
    
    Changes to be committed:
        modified:   lib/dnsruby/resource/DNSKEY.rb

[openssl::PKey::RSA.patch.zip](https://github.com/alexdalitz/dnsruby/files/1951488/openssl.PKey.RSA.patch.zip)

**Comment by edfeu** [comment]
This test ?
./tc_dnskey.rb 
Run options: --seed 52271

# Running:

DnskeyTest | ....
           | 0.00 s
Slowest tests:
0.00 s  DnskeyTest#test_dnskey_from_string
0.00 s  DnskeyTest#test_bad_values
0.00 s  DnskeyTest#test_dnskey_from_data
0.00 s  DnskeyTest#test_from_string_with_comments
Slowest suites:
0.00 s  DnskeyTest

Finished in 0.002743s, 1458.4663 runs/s, 4740.0156 assertions/s.

4 runs, 13 assertions, 0 failures, 0 errors, 0 skips

That's the same error I got before the patch.

I suspect if you modify lines 301 and 302 to respectively retrieve the exception and print it in the message, you'll see it's about an API error.

The openssl installed by "gem install openssl" is  (default: 2.1.0).  It's also the version on a Windows machine.

**Comment by alexdalitz** [comment]
OK, thanks for that. I'll try to find some time to look at this properly over the weekend.

Thanks!

**Comment by alexdalitz** [comment]
So I guess that I really need to work out which version of Ruby (and therefore (and also) which version of openssl) we're running on, and then make the appropriate call for the appropriate platform. I'll try to get this done soon. Thanks!

**Comment by alexdalitz** [comment]
OK, I've applied your patch, with a fallback to the old openssl interface. If you have the chance, could you please try master and let me know if it works for you? Please re-open this issue if there are any concerns.
I'll try to make a new release of dnsruby soon, once enough time has elapsed to allow any negative responses...
Thanks!

**Comment by ediazfer** [comment]
I've got the opportunity to test the current version of dnsruby and it appears to working.
I suspect the change in the openssl wrapper is to match the libssl API change.
Hence the same patch will probably need to be applied for the DSA key part of the code: .set_pgq(p,q,g)

**Comment by alexdalitz** [comment]
Ok - thanks for this. Could you please check over the latest commit and see if it looks sensible?

**Comment by edfeu** [comment]
I've added NSEC3DSA (algorithm 6) keys to test the fix but I've hit :

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by alexdalitz** [comment]
Can you post what you've got on a branch and I'll take a look?

**Comment by edfeu** [comment]
I've double checked (compared with my own C code using the new SSL API), and everything looks fine (meaning it matches the exact same steps as you do).
Please find attached a sample code meant to verify DS are generated properly for parsed DNSKEYs.
On my system (dnsruby trunk, ruby 2.5.1) it breaks at the first DSA record.

[instanciate-dnssec-keys.rb.gz](https://github.com/alexdalitz/dnsruby/files/1973565/instanciate-dnssec-keys.rb.gz)

**Comment by alexdalitz** [comment]
Just to say that I'm very sorry that it's taken me so long to look at this - it's been a hugely busy fortnight :(
I'll try very hard to find time for this over the next few days...

**Comment by edfeu** [comment]
Don't worry about it. There is only 24 hours in a days and there are always priorities.

**Comment by alexdalitz** [comment]
Sorry about the delay.

I'm trying this with ruby 2.5.1, dnsruby master, and your test file seems to work OK.

Do you still see problems with it, please?

**Comment by alexdalitz** [comment]
Given that I can run the supplied file no problem with Ruby 2.5.1, I'm going to close this issue now. Thanks for your help! If there is still a problem, feel free to re-open this.
