### ISSUE TITLE
dnsruby 1.60.1 breaks https://github.com/opendnssec/dnssec-monitor

### ISSUE THREAD

**Issue by stasic** [alexdalitz/dnsruby#150]
Here is a Dockerfile which shows how dnsruby 1.60.1 breaks https://github.com/opendnssec/dnssec-monitor
dnsruby Versions which work are 1.58, 1.59, 1.60.0

cat \<\<EOF >Dockerfile
FROM debian:stretch-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    ruby \
    gem \
    wget \
    unzip \
    dnsutils \
    vim-tiny \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN gem install -r dnsruby -v 1.58 && gem install -r soap2r
RUN wget https://github.com/opendnssec/dnssec-monitor/archive/master.zip
RUN unzip master.zip

WORKDIR /dnssec-monitor-master/lib/
RUN dig . dnskey > root.key

CMD ./nagios_dnssec.rb -z at --rootkey root.key -n j.ns.at -v
EOF

_build docker container:_
docker build -t "nagios-dnssec:stretch" .

_run bash within the container:_
docker run -it nagios-dnssec:stretch bash

_run command with working version 1.58 within the container:_
./nagios_dnssec.rb -z at --rootkey root.key -n j.ns.at -v

_install newer dnsruby version within the container:_
gem install -r dnsruby -v 1.60.1

_run command with broken version 1.60.1 within the container:_
./nagios_dnssec.rb -z at --rootkey root.key -n j.ns.at -v

**Comment by alexdalitz** [comment]
Does the latest version (1.61.2) work?

**Comment by stasic** [comment]
No, every single version since 1.60.0 is broken and all fail at the same stage.
```
./nagios_dnssec.rb -z at --rootkey root.key -n j.ns.at -v
DNSSEC OK:  : No IPv6 connectivity - not checking AAAA NS records
DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	256 3 RSASHA256 ( AwEAAdp440E6Mz7c+Vl4sPd0lTv2Qnc85dTW64j0RDD7sS/zwxWDJ3QRES2VKDO0OXLMqVJSs2YCCSDKuZXpDPuf++YfAu0j7lzYYdWTGwyNZhEaXtMQJIKYB96pW6cRkiG2Dn8S2vvo/PxW9PKQsyLbtd8PcwWglHgReBVp7kEv/Dd+3b3YMukt4jnWgDUddAySg558Zld+c9eGWkgWoOiuhg4rQRkFstMX1pRyOSHcZuH38o1WcsT4y3eT0U/SR6TOSLIB/8Ftirux/h297oS7tCcwSPt0wwry5OFNTlfMo8v7WGurogfk8hPipf7TTKHIi20LWen5RCsvYsQBkYGpF78= ) ; key_tag=2134
DNSSEC OK: DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	257 3 RSASHA256 ( AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0= ) ; key_tag=19036
DNSSEC OK: DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	257 3 RSASHA256 ( AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ) ; key_tag=20326
DNSSEC OK: DNSSEC OK:  : Making resolver for : j.ns.at, j.ns.at
DNSSEC OK:  : Checking at zone on j.ns.at(j.ns.at) nameserver
DNSSEC OK:  : (j.ns.at): Adding ksk : 56489
DNSSEC OK:  : (j.ns.at): Adding zsk : 31186
DNSSEC OK:  : (j.ns.at): Adding ksk : 26039
DNSSEC OK:  : (j.ns.at): at, DNSKEY verified OK
DNSSEC OK:  : (j.ns.at): at, SOA verified OK
DNSSEC OK:  : (j.ns.at): at, NS verified OK
DNSSEC OK:  : (j.ns.at): Checking non-existing domain for dklfjhwiouy4r9cefuyenwfuyenw.at, NS
DNSSEC CRITICAL:  : Can't find authoritative servers for  : 
DNSSEC WARNING:  : Failed to check j.ns.at(j.ns.at) : exit
```

**Comment by alexdalitz** [comment]
Could it be something to do with this?

## v1.60.1

* DNSSEC validation switched OFF by default (but can still be switched on)

**Comment by stasic** [comment]
No, still broken.
It seems that the zone got somehow lost. If you look at the output of the second last line there is a space ' ' and no zone any more.
(by the way: are you also the author of https://github.com/opendnssec/dnssec-monitor ?)
```
./nagios_dnssec.rb -z at --rootkey root.key -n j.ns.at -v
DNSSEC OK:  : No IPv6 connectivity - not checking AAAA NS records
DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	256 3 RSASHA256 ( AwEAAdp440E6Mz7c+Vl4sPd0lTv2Qnc85dTW64j0RDD7sS/zwxWDJ3QRES2VKDO0OXLMqVJSs2YCCSDKuZXpDPuf++YfAu0j7lzYYdWTGwyNZhEaXtMQJIKYB96pW6cRkiG2Dn8S2vvo/PxW9PKQsyLbtd8PcwWglHgReBVp7kEv/Dd+3b3YMukt4jnWgDUddAySg558Zld+c9eGWkgWoOiuhg4rQRkFstMX1pRyOSHcZuH38o1WcsT4y3eT0U/SR6TOSLIB/8Ftirux/h297oS7tCcwSPt0wwry5OFNTlfMo8v7WGurogfk8hPipf7TTKHIi20LWen5RCsvYsQBkYGpF78= ) ; key_tag=2134
DNSSEC OK: DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	257 3 RSASHA256 ( AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0= ) ; key_tag=19036
DNSSEC OK: DNSSEC OK:  : Loaded key from root.key : .	45824	IN	DNSKEY	257 3 RSASHA256 ( AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ) ; key_tag=20326
DNSSEC OK: DNSSEC OK:  : Making resolver for : j.ns.at, j.ns.at
DNSSEC OK:  : Checking at zone on j.ns.at(j.ns.at) nameserver
DNSSEC OK:  : (j.ns.at): Adding zsk : 31186
DNSSEC OK:  : (j.ns.at): Adding ksk : 56489
DNSSEC OK:  : (j.ns.at): Adding ksk : 26039
DNSSEC OK:  : (j.ns.at): at, DNSKEY verified OK
DNSSEC OK:  : (j.ns.at): at, SOA verified OK
DNSSEC OK:  : (j.ns.at): at, NS verified OK
DNSSEC OK:  : (j.ns.at): Checking non-existing domain for dklfjhwiouy4r9cefuyenwfuyenw.at, NS
DNSSEC CRITICAL:  : Can't find authoritative servers for  : 
DNSSEC WARNING:  : Failed to check j.ns.at(j.ns.at) : exit
```

**Comment by alexdalitz** [comment]
Yes, I was also the author of the dnssec-monitor, in a former life.

**Comment by alexdalitz** [comment]
Arsen - I'm very sorry that the dnssec-monitor is no longer playing nicely with dnsruby.

I wrote dnsruby a long time ago, and spend a reasonable amount of my spare time maintaining it for community use up to today.

I actually had forgotten about the existence of dnssec-monitor until today. I wrote it to monitor the .uk zone for a previous employer. I understand that it still monitors several country top level domain registries around the world (and possibly others).

I feel bad about not supporting dnssec-monitor - but it is not software which my current consultancy maintains.

If you feel strongly about support for dnssec-monitor, then I'd be happy to provide it - but this would have to be on a commercial basis, through my consultancy.

I understand that this is not what you want to hear - but there is a limit to the number of historical open source projects which I can support for free.

Thanks,


Alex.

**Comment by stasic** [comment]
Alex

Thank you for your quick reply and your information.

Best regards,
arsen

**Comment by alexdalitz** [comment]
OK - as it happens, I've got some spare time at the moment, so I will take a look at this and try to come up with a fix. Sorry about the time taken :-(

**Comment by alexdalitz** [comment]
@stasic I think the message I posted in the open-dnssec forum should solve your issue?

**Comment by alexdalitz** [comment]
Hi @stasic  - 

The fix I suggested works for me, and I haven't had any response from you, so I'm going to close this issue now.

If you find you are still having problems, please feel free to re-open this issue, or raise a new one - however, I'm pretty convinced that this issue is resolved since February.

Thanks,


Alex.
