### ISSUE TITLE
dnsruby freezes (very rarely)

### ISSUE THREAD

**Issue by fschwahn** [alexdalitz/dnsruby#152]
We have had this happen two times in a year, for a task that runs daily, so it is very rare. 

We have the following script (I abbreviated it a bit):

```ruby
resolver = Dnsruby::Resolver.new(nameserver: ["8.8.8.8", "8.8.4.4"])
resolver.retry_times = 3
record_type = "MX"

domains.each do |domain|
  begin
    response = resolver.query(domain, record_type)
    if response.header.ancount == 0
      puts "Missing #{record_type} record for domain \"#{domain}\""
    end
  rescue Dnsruby::NXDomain
    puts "Domain \"#{domain}\" does not exist"
  rescue Dnsruby::ResolvTimeout, Dnsruby::ServFail, Dnsruby::ResolvError, Dnsruby::OtherResolvError
    puts "Error trying to resolve domain \"#{domain}\""
  end
end
```

The job was killed after 24h, with the following stack trace:
```
File "/app/vendor/bundle/ruby/2.5.0/gems/dnsruby-1.61.2/lib/dnsruby/resolver.rb", line 253, in pop
File "/app/vendor/bundle/ruby/2.5.0/gems/dnsruby-1.61.2/lib/dnsruby/resolver.rb", line 253, in send_message
File "/app/vendor/bundle/ruby/2.5.0/gems/dnsruby-1.61.2/lib/dnsruby/resolver.rb", line 203, in query
```

This does not run in a multi-threaded environment, but as a dedicated process which runs this task.

**Comment by alexdalitz** [comment]
Hmmm.... This one is going to be very tricky to reproduce, and the stack trace doesn't really give me anything to go on. It sounds like something is getting locked up in the select thread. Can you provide any more details at all on this please?

**Comment by fschwahn** [comment]
Unfortunately there's not more to it. I added how we initialize the resolver to the code snippet, but I doubt it'll help much. The script ran for 18 minutes before it froze. It was run on ruby 2.5.5, and this task is run as a rake task. We start a dedicated heroku dyno for this task (ie. it is a completely isolated process).

**Comment by alexdalitz** [comment]
Do you know which domain it crashed on?

Is each domain resolved sequentially, in a single thread?

Thanks!

**Comment by fschwahn** [comment]
> Do you know which domain it crashed on?

Unfortunately not

> Is each domain resolved sequentially, in a single thread?

Yes

**Comment by alexdalitz** [comment]
Did you by any chance many to store the log?

If not - is it please possible to set the log level to DEBUG and capture the end of the log (last few thousand lines) in the case of a failure? If I had the log, I could probably fix this - without it, it’s going to be very hard….

Thanks!

**Comment by fschwahn** [comment]
Ok, I added code for this, but as I said: this is very rare. So don't be surprised if you don't hear anything from me for a few months.

**Comment by alexdalitz** [comment]
Thank you!

**Comment by alexdalitz** [comment]
Are you using TCP or UDP, please?

**Comment by fschwahn** [comment]
> Are you using TCP or UDP, please?

I don't know to be honest, but the code above includes all the interaction we have with Dnsruby - initializing a resolver, setting `retry_times,` and then querying. So we never explicitly configure anything with TCP / UDP.

**Comment by alexdalitz** [comment]
@fschwahn  - "Ok, I added code for this, but as I said: this is very rare. So don't be surprised if you don't hear anything from me for a few months."

Can I assume that this is no longer a problem, please?

Or do you now have some trace I can work with?

**Comment by fschwahn** [comment]
In the end we switched to `Resolv::DNS` because it is part of the standard library, and the functionality it provided is enough for our use case. I'll close this.
