### ISSUE TITLE
Resolver#query returns wrong answer types

### ISSUE THREAD

**Issue by isabanin** [alexdalitz/dnsruby#160]
Trying to get TXT records for a subdomain but getting a CNAME record instead. Am I missing something here?

```
>> Dnsruby::Resolver.new.query("domain.com", Dnsruby::Types.TXT).answer.map(&:type)
=> [CNAME, TXT]
```

**Comment by alexdalitz** [comment]
I ran this :

'''require 'dnsruby'

puts Dnsruby::Resolver.new.query("domain.com", Dnsruby::Types.TXT).answer.map(&$
'''

and got : 

'''TXT
TXT'''

Can I ask what dnsruby version you are using please?

Thanks,

Alex.

**Comment by isabanin** [comment]
I'm using 1.61.3. Can you try reproducing this with _dmarc.dmarcdigests.dev?

**Comment by alexdalitz** [comment]
irb(main):003:0> Dnsruby::Resolver.new.query("_dmarc.dmarcdigests.dev", Dnsruby::T
=> [CNAME, TXT]

% dig _dmarc.dmarcdigests.dev txt  

; <<>> DiG 9.10.6 <<>> _dmarc.dmarcdigests.dev txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39701
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;_dmarc.dmarcdigests.dev.	IN	TXT

;; ANSWER SECTION:
_dmarc.dmarcdigests.dev. 48	IN	CNAME	example.com.
example.com.		86388	IN	TXT	"v=spf1 -all"

;; Query time: 129 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Apr 21 15:46:12 BST 2020
;; MSG SIZE  rcvd: 124


It all looks good to me!

**Comment by isabanin** [comment]
Alright, you can disregard this ticket then. Looks like I'm missing something about the way DNS look-ups work 😅
