### ISSUE TITLE
_acme-challege TXT record does not work 

### ISSUE THREAD

**Issue by ravensnowbird** [alexdalitz/dnsruby#162]
Let's Encrypt uses "_acme-challenge.www.example.com" pattern to verify domain ownership through DNS. 

Dnsruby::DNS.new.getresources("_acme-challenge.www.example.com", Dnsruby::Types.TXT)

=> Dnsruby::NXDomain (Dnsruby::NXDomain)

**Comment by alexdalitz** [comment]
% dig _acme-challenge.www.example.com

; <<>> DiG 9.10.6 <<>> _acme-challenge.www.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39132
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;_acme-challenge.www.example.com. IN	A

;; AUTHORITY SECTION:
example.com.		3600	IN	SOA	ns.icann.org. noc.dns.icann.org. 2019121395 7200 3600 1209600 3600

;; Query time: 181 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri May 22 08:27:33 BST 2020
;; MSG SIZE  rcvd: 127

**Comment by alexdalitz** [comment]
I think I've shown that dnsruby is behaving correctly here, so I'm going to close this issue now.

If you can demonstrate an issue with dnsruby, then please feel free to reopen this, or create a new issue.

Thanks!
