### ISSUE TITLE
CAA request resolve CNAME

### ISSUE THREAD

**Issue by nagavijayan-nagarathinam** [alexdalitz/dnsruby#167]
When i try to resolve CAA using DNSruby, i used to get CNAME answer.

pfa

<img width="1275" alt="Screenshot 2020-10-07 at 7 06 32 PM" src="https://user-images.githubusercontent.com/53569528/95339553-ccacdd00-08d1-11eb-97c6-9253d1ad3ff3.png">

**Comment by alexdalitz** [comment]
Could you please post the results of a dig for the same query?

**Comment by nagavijayan-nagarathinam** [comment]
<img width="550" alt="Screenshot 2020-10-07 at 7 29 51 PM" src="https://user-images.githubusercontent.com/53569528/95341464-ec450500-08d3-11eb-9820-752048b689e2.png">

**Comment by alexdalitz** [comment]
So I think you’re getting the same answer from dig as from dnsruby, right?

I think the idea of CAA validation is that it follows the CNAMEs until it finds a CAA record. However, dig and dnsruby are simply returning the results of the original query, which I believe is the correct behaviour - they do not do CAA validation.
