### ISSUE TITLE
NoMethodError undefined method `[]' for nil:NilClass on CAA lookup

### ISSUE THREAD

**Issue by dbackeus** [alexdalitz/dnsruby#168]
Running:
```ruby
Dnsruby::Resolver.new.query("nccgroup.com", Dnsruby::Types::CAA)
```

I get the error:
```
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/davidbackeus/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dnsruby-1.61.4/lib/dnsruby/resource/CAA.rb:47:in `from_string'
```

**Comment by alexdalitz** [comment]
Thanks for this!

It turns out that Dnsruby did not handle contactemail or contactphone.

I’ve added support to them for the master branch. Would it be possible to give it a shot, please?

Thanks!


Alex.

**Comment by dbackeus** [comment]
Totally works now, thanks!

Would appreciate, if you have the time, if you could push a new gem release to avoid having to use `git: ` in the Gemfile.

**Comment by alexdalitz** [comment]
Sure, I can do that. However, it might take me a day or two to get a release together. I’ll leave this issue open until I’ve made a release, after which I’ll close it. So you should get a notification by that means that a new release is available.

Thanks!

**Comment by alexdalitz** [comment]
Ok - Dnsruby v1.61.5 is now released :)
