### ISSUE TITLE
incorrect TXT segment parsing

### ISSUE THREAD

**Issue by and0x000** [alexdalitz/dnsruby#170]
The [TXT parsing function](https://github.com/alexdalitz/dnsruby/blob/master/lib/dnsruby/resource/TXT.rb#L52) fails to recognized segmented records, that consist of escaped and non-escaped strings.

Example:

```
@ IN TXT "a" b
```
This is a legal TXT record, consisting of the 2 segments `a` and `b`. Running this through the TXT parser, it gives me an array only containing `a`.

minimal working example:

```ruby
~ pry
[1] pry(main)> require 'dnsruby'
=> true
[2] pry(main)> Dnsruby::RR::TXT.parse 'a b'
=> ["a", "b"] # OK
[3] pry(main)> Dnsruby::RR::TXT.parse '"a" "b"'
=> ["a", "b"] # OK
[4] pry(main)> Dnsruby::RR::TXT.parse '"a" b'
=> ["a"] # NOK
```

**Comment by and0x000** [comment]
This seems to only happen, when the parsed string is inside single quotation marks, i.e. without escaping the double quotation marks due to not being necessary.

Is this considered valid input for this gem or did I stumble upon a non-real-world edge case?

**Comment by and0x000** [comment]
The problem seems to be caused by this section in the code

```ruby
[...]
          next if seen_strings && !in_string # resolves to true
[...]
```

In the iteration, where `b` would have to be added to the array, `seen_strings` is `true` and `in_string` is false, resulting in the call to `next`, skipping `b`.

**Comment by alexdalitz** [comment]
Oh dear how terrifically embarrassing! Thanks for the report. I’ll try to get this fixed over the weekend

**Comment by and0x000** [comment]
> Oh dear how terrifically embarrassing!

It's hardly embarrassing, considering what a f***ed up mess TXT records are to parse/validate. I'm glad someone else accepted this challenge.

On the topic of being a mess: When fixing this, please be aware that `"a" b` (with whitespace in between) is valid TXT data, whereas `"a"b` (without whitespace in between) is not ... this gave me headaches to the point of resignation when I tried to fix this myself. Not entirely sure thought, if receiving/handling possibly incorrect DNS data is in the scope of this gem.

**Comment by alexdalitz** [comment]
OK, I've pushed a fix which parses your examples. To be honest, it's far from clear whether this is actually correct behaviour or not!

**Comment by and0x000** [comment]
> OK, I've pushed a fix which parses your examples.

Thank you very much.

> To be honest, it's far from clear whether this is actually correct behaviour or not!

Not sure to what point exactly you are refering to, but there are indeed differences across implementations for what constitudes a legit TXT record.

Probably way beyond the scope of this issue but: I cross-tested with `named-checkzone` (bind9), `nsd-checkzone` and `kzonecheck` (knot) for zonefile validation. Interestingly enough, only `named-checkzone` accepts a txt record without whitespace between string `"a"` and `b`. WTF. All 3 are solid DNS server implementations so a majority vote of what constitutes for valid would be plausible, if it weren't for the fact, that bind is the refference implementation.
