### ISSUE TITLE
Error in v1.61.6 `undefined method []=' for #<Dnsruby::cache`

### ISSUE THREAD

**Issue by andyw8** [alexdalitz/dnsruby#176]
I'm seeing this error in v1.61.6, but not in v1.61.5.

**Comment by alexdalitz** [comment]
Do you have a stack trace please?

**Comment by andyw8** [comment]
Nothing useful... I think this may be the same issue as https://github.com/alexdalitz/dnsruby/issues/175, and it's calling `Dnsruby::Cache` instead of the app's own `Cache` class.

**Comment by alexdalitz** [comment]
Yes, that’s probably the case.

Sorry - we will get this fixed very soon and a new gem released.

**Comment by alexdalitz** [comment]
OK, I've merged a PR with master which should fix this issue.
I'll release a dnsruby1.61.7 gem now.
Profuse apologies for the inconvenience...
Please let me know if you still have problems with the new version
