### ISSUE TITLE
dynamic updates with more than 255 characters fail (Dnsruby::TsigNotSignedResponseError)

### ISSUE THREAD

**Issue by raemer** [alexdalitz/dnsruby#187]
Hi,

I'm trying to use dnsruby to manage bind via puppet. This works so far, but I cannot add long TXT records (DKIM key). Once the dynamic update message is more than 255 characters long, it seems not to be signed any more.
I build a minimal example for one working (255 chars) and one failing (256 chars) request (see below) and recorded a tcpdump.

Best regards,
Jan-Martin

Minimal example:
```
irb(main):197:0> str255='';255.times { str255+='1' }
=> 255
irb(main):198:0> str256='';256.times { str256+='1' }
=> 256
irb(main):199:2* tsig = Dnsruby::RR::TSIG.new({
irb(main):200:2*     name: "local-ddns",
irb(main):201:2*     algorithm: 'hmac-sha256',
irb(main):202:2*     key: "[removed]",
irb(main):203:0>   })
=> #<Dnsruby::RR::TSIG:0x000056203575e828 @algorithm=#<Dnsruby::Name: hmac-sha256.>, @fudge=300, @mac_size=0, @mac="", @original_id=15096, @error=0, @other_size=0, @other_data="", @time_signed=nil, @buf=nil, @klass=ANY, @ttl=0, @name=#<Dnsruby::Name: local-ddns.>, @key="V5A8nhKD1high7nc4K/SnXzaphtUxbciUDd+x1o5pwU=">
irb(main):204:0> @resolver = Dnsruby::Resolver.new({ nameserver: '::1',})
=> #<Dnsruby::Resolver:0x0000562035749a40 @resolver_ruby=nil, @src_address=nil, @src_address6=nil, @single_res_mutex=#<Thread::Mutex:0x00005620357499f0>, @configured=true, @do_caching=true, @config=Config - nameservers : ::1,  domain : empty, search : intern.zit-rlp.de,  ndots : 1 port : 53, @do_validation=false,...
irb(main):205:0> @resolver.tsig = tsig
=> #<Dnsruby::RR::TSIG:0x000056203575e828 @algorithm=#<Dnsruby::Name: hmac-sha256.>, @fudge=300, @mac_size=0, @mac="", @original_id=15096, @error=0, @other_size=0, @other_data="", @time_signed=nil, @buf=nil, @klass=ANY, @ttl=0, @name=#<Dnsruby::Name: local-ddns.>, @key="V5A8nhKD1high7nc4K/SnXzaphtUxbciUDd+x1o5pwU=">
irb(main):206:0> update = Dnsruby::Update.new('example.com')
=> #<Dnsruby::Update:0x00005620353bf5f0 @header=#<Dnsruby::Header:0x00005620353bf528 @id=64097, @qr=false, @opcode=Update, @aa=false, @ad=false, @tc=false, @rd=0, @ra=false, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=0, @arcount=0>, @question=[#<Dnsruby::Question:0x00005620353bec68 @qtype=SOA, @q...
irb(main):207:0> update.add('test.example.com', Dnsruby::Types.TXT, 86400, str255)
=> #<Dnsruby::RR::IN::TXT:0x00005620356012f0 @rdata="'111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'", @strings=["111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"], @name=#<Dnsruby::Name: test.example.com>, @ttl=86400, @type=TXT, @klass=IN>
irb(main):208:0> @resolver.send_message(update)
=> #<Dnsruby::Message:0x0000562035732868 @header=#<Dnsruby::Header:0x0000562035732340 @id=64097, @qr=true, @opcode=Update, @aa=false, @ad=false, @tc=false, @rd=false, @ra=false, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=0, @arcount=0>, @question=[#<Dnsruby::Question:0x0000562035731a80 @qtype=SOA, @qclass=IN, @qname=#<Dnsruby::Name: example.com.>>], @answer=[], @authority=[], @additional=[], @tsigstate=:Verified, @signing=false, @tsigkey=nil, @answerfrom="::1", @answerip="::1", @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=false, @answersize=112, @tsigstart=29, @tsigerror=NOERROR>
irb(main):209:0> @resolver = Dnsruby::Resolver.new({ nameserver: '::1',})
=> #<Dnsruby::Resolver:0x00005620357353b0 @resolver_ruby=nil, @src_address=nil, @src_address6=nil, @single_res_mutex=#<Thread::Mutex:0x0000562035735360>, @configured=true, @do_caching=true, @config=Config - nameservers : ::1,  domain : empty, search : intern.zit-rlp.de,  ndots : 1 port : 53, @do_validation=false,...
irb(main):210:0> @resolver.tsig = tsig
=> #<Dnsruby::RR::TSIG:0x000056203575e828 @algorithm=#<Dnsruby::Name: hmac-sha256.>, @fudge=300, @mac_size=0, @mac="", @original_id=15096, @error=0, @other_size=0, @other_data="", @time_signed=nil, @buf=nil, @klass=ANY, @ttl=0, @name=#<Dnsruby::Name: local-ddns.>, @key="V5A8nhKD1high7nc4K/SnXzaphtUxbciUDd+x1o5pwU...
irb(main):211:0> update = Dnsruby::Update.new('example.com')
=> #<Dnsruby::Update:0x00005620353be9c0 @header=#<Dnsruby::Header:0x00005620353be808 @id=30872, @qr=false, @opcode=Update, @aa=false, @ad=false, @tc=false, @rd=0, @ra=false, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=0, @arcount=0>, @question=[#<Dnsruby::Question:0x00005620353bd890 @qtype=SOA, @q...
irb(main):212:0> update.add('test.example.com', Dnsruby::Types.TXT, 86400, str256)
=> #<Dnsruby::RR::IN::TXT:0x0000562035535bf0 @rdata="'1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'", @strings=["1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"], @name=#<Dnsruby::Name: test.example.com>, @ttl=86400, @type=TXT, @klass=IN>
irb(main):213:0> @resolver.send_message(update)
Traceback (most recent call last):
        5: from /usr/bin/irb:23:in `<main>'
        4: from /usr/bin/irb:23:in `load'
        3: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        2: from (irb):213
        1: from /usr/lib/ruby/vendor_ruby/dnsruby/resolver.rb:257:in `send_message'
Dnsruby::TsigNotSignedResponseError (Dnsruby::TsigNotSignedResponseError)
```
Traffic dump:
[dns.pcap.zip](https://github.com/alexdalitz/dnsruby/files/12047537/dns.pcap.zip)

**Comment by alexdalitz** [comment]
Hi - 

There is a limit of 255 characters on a single string in a TXT record : https://kb.isc.org/docs/aa-00356

Perhaps this is the cause of the issue?

Thanks,

Alex.

**Comment by raemer** [comment]
Hi,

thanks for the link (pointing to a workaround), but I think there is still something wrong. The issue also occured with a read DKIM record (one string with blocks enclosed in `"` and each below 255 characters). I also tried again with the real record and compared it to the same request done with nsupdate. Both seem to ignore the 255 character limit (which recent bind versions don't seem to care about), but decoding in wireshark, the dnsruby packet's last block is shown as
```
xX7HZAh3g3HnNa+yyaASmYRmGAtuMzgoCw9fL6oPtm6RuojF4veMbbQIDAQAB"
local-ddnsúÿ=hma
```
i.e. the start of the TSIG (`local-ddns...`) is parsed as part of the TXT block.
I attached a trace of only the two packets with the real record (first packet from nsupdate, second from dnsruby).

Best regards,
Jan-Martin
[dns2.pcap.zip](https://github.com/alexdalitz/dnsruby/files/12048613/dns2.pcap.zip)

**Comment by alexdalitz** [comment]
Could you please send me some test code which demonstrates the problem?

**Comment by raemer** [comment]
Hi,

I generated a dump like in my last comment by running 
`echo -e "server ::1\n\nadd test.example.com 300 txt \"v=DKIM1; h=sha256; k=rsa; \" \"p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnC51J0sQ9J6cGO8sJKbfLqbNdH7odE38smTG6OW5+LPJjyrd4TkX6vMqaeJJULsJXaLd0hVFXTBHZhQtFHCT2HVupL305F5IMdWW9fYtCS5siaNtmB3wfh2VyVKS5YIZqBaKEF5m6TRsXIg/uDnq+kdjbcrjNTaSEg7FVFxVvu9b9Frdf1jeHxfF/hjUmigsDRfsESt3vm5AFS\" \"QEDtuJEb7md23GNdm13FiZt8nOlwLU8Oz+ILOPSQ653sauHqFdskI0OLl2P3GfVF/9pMne2vqHoYOWHBXxX7HZAh3g3HnNa+yyaASmYRmGAtuMzgoCw9fL6oPtm6RuojF4veMbbQIDAQAB\"\n\nsend" |nsupdate -k /run/named/session.key`
and this script (with key=key from /run/named/session.key)
[test.rb.txt](https://github.com/alexdalitz/dnsruby/files/12067607/test.rb.txt),
i.e. sending the same request via nsupdate and then via dnsruby. The first one adds this line to the zone file:
`test                    TXT     "v=DKIM1; h=sha256; k=rsa; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnC51J0sQ9J6cGO8sJKbfLqbNdH7odE38smTG6OW5+LPJjyrd4TkX6vMqaeJJULsJXaLd0hVFXTBHZhQtFHCT2HVupL305F5IMdWW9fYtCS5siaNtmB3wfh2VyVKS5YIZqBaKEF5m6TRsXIg/uDnq+kdjbcrjNTaSEg7FVFxVvu9b9Frdf1jeHxfF/hjUmigsDRfsESt3vm5AFS" "QEDtuJEb7md23GNdm13FiZt8nOlwLU8Oz+ILOPSQ653sauHqFdskI0OLl2P3GfVF/9pMne2vqHoYOWHBXxX7HZAh3g3HnNa+yyaASmYRmGAtuMzgoCw9fL6oPtm6RuojF4veMbbQIDAQAB"` (i.e. not splitted into multiple records of less than 255 byes each), the second one exits with `/usr/lib/ruby/vendor_ruby/dnsruby/resolver.rb:257:in `send_message': Dnsruby::TsigNotSignedResponseError (Dnsruby::TsigNotSignedResponseError)`.

Best regards,
Jan-Martin

**Comment by raemer** [comment]
Hi,

thanks for the pointer, splitting my record at each space and passing it as an array works.

Best regards,
Jan-Martin
