### ISSUE TITLE
Resolving A record as CNAME

### ISSUE THREAD

**Issue by Rudis1261** [alexdalitz/dnsruby#199]
Hi there,

We are having an issue where when you query for a particular record type for a domain, I am getting a different record type back. 

IE: i am resolving `www.heidi.trial.co.za`'s A record, my expectation is that if that is a CNAME, it should continue resolving the record until the A record is returned. 

Instead, I need to interrogate the result and when it's a CNAME continue tracing it on the domainname until it reaches the A record. Is this expected behaviour or a bug?

**Comment by alexdalitz** [comment]
Could you send some code which shows the issue, please?

**Comment by Rudis1261** [comment]
Oh sorry yeah we were being daft :-D You return all the answers so for a CNAME it has both the CNAME as well as the final A record. We were incorrectly assuming we would only receive the final answer.
