### ISSUE TITLE
CAA records with mixed case or uppercase property tags cause parsing errors

### ISSUE THREAD

**Issue by ruby-dev** [alexdalitz/dnsruby#201]
When using using Dnsruby to lookup and parse CAA records that contain mixed case or uppercase property tags cause the code to generate an exception.

```
Lookup CAA records for uppercase-deny.basic.caatestsuite.com
An error occurred (Dnsruby::DecodeError): Cannot parse record: 0 ISSUE "caatestsuite.com"

Lookup CAA records for mixedcase-deny.basic.caatestsuite.com
An error occurred (Dnsruby::DecodeError): Cannot parse record: 0 IsSuE "caatestsuite.com"
```

Per RFC 8659, Section 3 identifiers are case-insensitive and these values are allowed.

"Property identifiers such as 'issue' or 'issuewild' are case-insensitive."

**Comment by alexdalitz** [comment]
Thanks!
This is now merged.
If you really need this in a release then please let me know.

**Comment by nsmethwick-fastly** [comment]
Hey @alexdalitz, we are running into the same issue, can you create a release for the fix that was merged?

**Comment by alexdalitz** [comment]
Sure! v1.72.4 is now released :-)

**Comment by nsmethwick-fastly** [comment]
Thank you!
