### ISSUE TITLE
Memleack

### ISSUE THREAD

**Issue by promix17** [alexdalitz/dnsruby#64]
Just run this code and get memleak: http://pastebin.com/grCKZqBN
dnsruby produces a lot of strange classes for every request and theese classes are unfree in ruby, because you can't free class definition

**Comment by alexdalitz** [comment]
Hi - 

> Just run this code and get memleak: http://pastebin.com/grCKZqBN <http://pastebin.com/grCKZqBN>
> dnsruby produces a lot of strange classes for every request and theese classes are unfree in ruby, because you can't free class definition
> 

I suspect that you are seeing the results of the Cache. Dnsruby maintains a cache of responses so that it doesn’t have to repeat queries unnecessarily. This behaviour can be switched off if desired.

It sounds like you would like there to be an option to close the cache. I’m not sure if the Resolver.close() method is the best place for that, as the Cache is shared and may be in use by other Resolvers. Perhaps a specific method to close the cache would help?

Thanks,


Alex Dalitz
alex@caerkettontech.com

**Comment by promix17** [comment]
Yes, thanks for explanation and sorry for my english.
Method for cleaning cache would help, but you can also provide cache limitation.
I've used dnsruby for brute and discover subdomains while pentesting, and when worker worked a lot it ate all memory. I think that every application should work infinity long and some limitation of cache is a good idea.

**Comment by alexdalitz** [comment]
> Method for cleaning cache would help, but you can also provide cache limitation.
> I've used dnsruby for brute and discover subdomains while pentesting, and when worker worked a lot it ate all memory. I think that every application should work infinity long and some limitation of cache is a good idea.
> 
I take your point.

I had thought that entries in the cache would expire when their TTLs expire, but that could be some time (often one week). I guess some sort of configurable limit to the cache size would be good.

I wonder how the limit should work? A simple solution would be just to refuse new entries while the cache is full - I’m not sure how easy or quick it would be to find the oldest records in order to expire them.

Thanks,


Alex Dalitz
alex@caerkettontech.com

**Comment by promix17** [comment]
I'm not so good expert at Ruby but the common solution in other languages is to limit cahe, and when it is full - remove the most old records - and no need ttl at all.
If hashes are ordered we can user Hash.shift:
```ruby
# We update cahe every time element accessed
def add(item)
  s = s.shift if s.size==@max_size
  s.delete(item.key) # nothing if not exists
  s[item.key]=item #add item
end
```

**Comment by alexdalitz** [comment]
Hi - 

> I'm not so good expert at Ruby but the common solution in other languages is to limit cahe, and when it is full - remove the most old records - and no need ttl at all.
> If hashes are ordered we can user Hash.shift:
> 
> # We update cahe every time element accessed
> def add(item)
>   s = s.shift if s.size==@max_size
>   s.delete(item.key) # nothing if not exists
>   s[item.key]=item #add item
> end
Thanks for this.

I’m not sure this will work to remove the _oldest_ record from the cache in dnsruby, but it would help implement some sort of cache limit.

I’m extraordinarily busy just now, but I’ll look at implementing something to test this evening.

Do you have any ideas on a sensible default size for the cache?

Thanks,


Alex Dalitz
alex@caerkettontech.com

**Comment by promix17** [comment]
Hello again,

I think, that cache size could be customizable and defauld size could be big enough up to 1000 records.

Previos code removes the oldest_ record becouse hash is ordered since ruby 1.9.
```ruby
def add(item)
   s.shift if s.size==@max_size # Of cource s.shift instead  s=s.shift
   s.delete(item.key) # nothing if not exists
   s[item.key]=item #add item
 end
```

**Comment by alexdalitz** [comment]
Hi - 

Sorry about the length of time it's taking for me to get this done. I've been super-busy recently - but I can confirm that this work will definitely be done before the next release of dnsruby (which I aim to make in the next few weeks).
In the meantime, perhaps the methods -
Dnsruby::PacketSender.clear_caches
Dnsruby::Recursor.clear_caches
might be useful for you?

Thanks,

Alex.

**Comment by promix17** [comment]
Hello,

You could not to hurry coding, thanks for fast support. 

Clear_caches method could help me, or even method to disable caches.

Thanks,
Michael

**Comment by alexdalitz** [comment]
The clear caches methods I showed are already there. You can also disable caching at either message or resolver level with the current release. See the docs on this site...

Hth

Alex.

**Comment by alexdalitz** [comment]
Hi -

Sorry about the extended delay.

Given my extreme business, I've been lazily wondering if it's possible that the concerns which led to this issue have been addressed by the methods discussed above?

If so, I'm inclined to leave the extra work of limiting the cache (although patches are always welcomed!) and perhaps just document the Cache class and its methods more clearly?

Please let me know your thoughts...

Thanks!


Alex.

**Comment by keithrbennett** [comment]
If this can't be done in the short term, that's totally understandable, but I think it's important enough to remain an open issue.

**Comment by alexdalitz** [comment]
Hi - 

I'm pleased to say that I have _finally_ introduced a Cache.max_size=() method to limit the cache size. Sorry about the extended delay!

I plan to release a new version of dnsruby extremely soon now - so any feedback would be very welcome!

Thanks,


Alex.
