### ISSUE TITLE
Recursor.@@nameservers gets set to bogus array

### ISSUE THREAD

**Issue by mcr** [alexdalitz/dnsruby#86]
When doing validation from the root, I see errors like:
    Argument nameserver not valid : invalid nameserver config: [#<Dnsruby::Recursor::AddressCache:0x000000071800e0 @hash={"199.7.91.13"=....

I have traced this to an initialization in recursor.rb, where it does:
             @resolver = Resolver.new({:nameserver => @@nameservers})
where @@nameservers is just not a list of name servers.
This occurs from Recursor.set_hints, which gets called from query() at: dnsruby/lib/dnsruby/recursor.rb:397.

(rdb:1) p hints
{"d.root-servers.net"=>#<Dnsruby::Recursor::AddressCache:0x00000005c995f0 @hash={"199.7.91.13"=>2015-05-08 17:30:54 -0400, "2001:500:2D::D"=>

The problem appears to be that the hints being collected are an AddressCache, which makes sense to me, but set_hints() doesn't know how to deal with this to make the @@nameservers.
The question is: should set_hints() cope (producing a sane array of strings), or should the initializer to in Resolver accept that it might get a hash of values that area address cache?

**Comment by mcr** [comment]
The other question is whether @@hints should retain the address cache values, and @@nameservers should be a basic list, or if @@hints should also contain just a plain list.

**Comment by alexdalitz** [comment]
Hi -

I just wanted to say thanks very much for the issue report, and apologies for the very slow response. My extreme business shouldn't prevent me from answering this for too much longer...

thanks!


Alex.

**Comment by alexdalitz** [comment]
Hi -

Thanks again for your issue report!

I think I have fixed this in c255cdc..3435352.

Please let me know if you still have issues.

Thanks!


Alex.
