### ISSUE TITLE
Cannot set validation policy

### ISSUE THREAD

**Issue by pzb** [alexdalitz/dnsruby#88]
```ruby
Dnsruby::Dnssec.validation_policy = Dnsruby::Dnssec::ValidationPolicy::ALWAYS_ROOT_ONLY
```

The above line causes a traceback because https://github.com/alexdalitz/dnsruby/blob/1e9dde4fd9069c74a2a89e608968cc089f1bbb13/lib/dnsruby/dnssec.rb#L69 has three issues: 
* `ALWAYS_ROOT_ONY` should be `ALWAYS_ROOT_ONLY`
* `ALWAYS_LOCAL_ANCHORS` should be `ALWAYS_LOCAL_ANCHORS_ONLY`
* Both need to be prefixed with `ValidationPolicy::`

**Comment by alexdalitz** [comment]
Thanks for this - this is now fixed in master.
I'm not sure what to say really, other than that I'm clearly a cretin.
Sorry about that.
Thanks!

Alex.

**Comment by pzb** [comment]
Nope, still no good.  The constants need to be prefixed with `ValidationPolicy::`.

**Comment by keithrbennett** [comment]
@pzb I don't think that's true.  This from irb:

```
.2.1 :001 > class C
2.2.1 :002?>   PI = 3.1415
2.2.1 :003?>   def foo
2.2.1 :004?>     puts PI
2.2.1 :005?>     end
2.2.1 :006?>   end
 => :foo
2.2.1 :007 > C.new.foo
3.1415
 => nil
```

**Comment by pzb** [comment]
Yes, but the code in dnsruby looks like this:

```ruby
class A
    class B
      SOME_CONST = 1
    end
    def foo
        puts SOME_CONST
    end
end
```

You need to use `B::SOME_CONST` not just plain `SOME_CONST`.

**Comment by keithrbennett** [comment]
Oh, I see, sorry about that.

**Comment by alexdalitz** [comment]
Should be working now
