### ISSUE TITLE
Documentation does not show how to update a PTR record

### ISSUE THREAD

**Issue by walls00000** [alexdalitz/dnsruby#92]
I would like to update a PTR record with dnsruby.  The documentation does not include any examples or reference to updating a PTR record.  I'd like to do the following . . . 

update.add('foo.example.com.', 'A', 86400, '192.168.1.2')
update.add('2.1.168.192.in-addr.arpa.', 'PTR', 86400, 'foo.example.com.')  

What is the correct way to do this?

**Comment by walls00000** [comment]
In my investigation I was able to make this work by removing update.absent or update.present.  Please add something to the documentation to help others.  Here is the code that worked for me . . . 

require 'rubygems'
require 'dnsruby'


KEY_NAME="rndc.key"
KEY = "XXXXXXXXXXXXXXXXXXXXXX=="

res = Dnsruby::Resolver.new({:nameserver => 'my.dns.server''})
res.tsig=KEY_NAME, KEY

# Create the update packet.
update = Dnsruby::Update.new('0.0.10.in-addr.arpa')
#update.absent('200.0.0.10.in-addr.arpa.', 'PTR') <==THIS SHOULD BE COMMENTED OUT
update.add('200.0.0.10.in-addr.arpa.', 'PTR', 86400, 'foo.example.com.')

begin
  reply = res.send_message(update)
  print reply
  print "Update succeeded\n"
rescue Exception => e
  print "Update failed: #{e}\n"
end

**Comment by alexdalitz** [comment]
OK - thanks!


Alex.

**Comment by alexdalitz** [comment]
I think this may well be fixed by the recent update-absent branch merge
