### ISSUE TITLE
Timeouts During Zone Transfer?

### ISSUE THREAD

**Issue by cdonadeo** [alexdalitz/dnsruby#93]
While the `Resolver` class allows setting timeouts, I could not find anything in the `ZoneTransfer` class that allows setting my own `Resolver` or directly setting timeouts.  In my testing, if the DNS server cannot be connected to, then `Errno::ETIMEDOUT` will be thrown after some amount of time, but it's not adjustable. I think it might be possible to hang entirely if connection succeeds but some sort of network issue prevents progress from being made, as I've had some background workers lock up in `ZoneTransfer#transfer`.

**Comment by alexdalitz** [comment]
Hi - 

Thanks very much for this report.

It certainly doesn’t sound ideal! I’m very busy just now, but will try to look at this over the next couple of days.

Thanks,


Alex.

**Comment by alexdalitz** [comment]
Sadly, the zone transfer code does not use the main networking system in dnsruby. This means that socket timeouts are an issue with the primitive send_message and receive_message methods in ZoneTransfer.
It would be pretty challenging to wire the zone transfer code up to use the main dnsruby network system. It would be easier to hack the receive_message and send_message methods in ZoneTransfer to implement timeouts using select.
Regarding lock-ups - I can believe it. The code does little to handle errors well, and assumes a happy path.
I guess this probably isn't what you want to hear...

**Comment by cdonadeo** [comment]
Thaks for taking a look!  That's a bit unfortunate.  I don't really understand how timeouts are implemented in the main networking system, but it does seem rather complex.

I read a bit about implementing timeouts for TCPSocket and was surprised to learn that is non-trivial as well.  Looking at a few different code bases, it seems that most projects implement a non-blocking socket using IO#select to wait for connection or timeout.  [This article](http://spin.atomicobject.com/2013/09/30/socket-connection-timeout-ruby/) has a good demonstration.  That would at least accomplish configurable connection timeouts.

There's also [Net::TCPClient](https://github.com/rocketjob/net_tcp_client) that implements connect, read, and write timeouts.  I've never used it, but it looks really neat.  I don't know how you feel about adding new dependencies though.

This isn't really a high priority issue for me, but if I get a chance I may take a stab at implementing something over the holidays.

**Comment by alexdalitz** [comment]
Sorry about the delay.
I've now added `zone_transfer.connect_timeout=` so you can set the connection timeout on the zone transfer.
Thanks!
