### ISSUE TITLE
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by dentarg** [alexdalitz/dnsruby#94]
``` ruby
[15] pry(main)> require "dnsruby"
=> true

[16] pry(main)> Dnsruby::DNS.new.getaddress("räksmörgås.josefßon.org")
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
from /Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:32:in `put_string'

[17] pry(main)> Error: incompatible character encodings: ASCII-8BIT and UTF-8
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:32:in `put_string'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:72:in `put_label'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:61:in `block in put_labels'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:54:in `each_index'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:54:in `put_labels'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:50:in `put_name'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/message.rb:553:in `block (2 levels) in encode'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/message.rb:552:in `each'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/message.rb:552:in `block in encode'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/encoder.rb:6:in `initialize'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/message.rb:549:in `new'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/message/message.rb:549:in `encode'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/packet_sender.rb:693:in `make_query_packet'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/packet_sender.rb:331:in `send_async'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:1007:in `block (3 levels) in tick'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:993:in `each'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:993:in `block (2 levels) in tick'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:983:in `each'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:983:in `block in tick'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:981:in `synchronize'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/resolver.rb:981:in `tick'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/select_thread.rb:807:in `block in send_tick_to_observers'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/select_thread.rb:806:in `each'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/select_thread.rb:806:in `send_tick_to_observers'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/select_thread.rb:171:in `do_select'
/Users/dentarg/.gem/ruby/2.2.3/gems/dnsruby-1.59.0/lib/dnsruby/select_thread.rb:70:in `block (2 levels) in initialize'

[17] pry(main)> RUBY_DESCRIPTION
=> "ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]"
```

Also strange: the second exception with the long backtrace pops out some seconds later after I have executed `Dnsruby::DNS.new.getaddress("räksmörgås.josefßon.org")` and gotten the first exception

**Comment by alexdalitz** [comment]
Ah yes - there is currently no punycode converter in dnsruby. So, if you want an IDN in a string, you currently have to convert it to punycode before using it in dnsruby (so you should end up with something like “xn—<stuff>” ).

I guess I should consider adding a punycode converter at some point…

HTH,


Alex.

**Comment by alexdalitz** [comment]
So I'm thinking about adding the simpleidn gem and using that for punycode conversion within dnsruby. Does that work for you?

**Comment by dentarg** [comment]
@alexdalitz actually, I would hesitate to use [simpleidn](https://github.com/mmriis/simpleidn), because that gem doesn't seem maintained anymore (no commit for over 2 years)

I would go with [addressable](https://github.com/sporkmonger/addressable), which is in fact what I use in my project to workaround this
```ruby
host = Addressable::URI.parse(url.to_s).normalized_host
```

though I have to admit: I'm not currently using dnsruby, I'm still using [resolv in stdlib](http://ruby-doc.org/stdlib-2.2.3/libdoc/resolv/rdoc/Resolv/DNS.html), but I might switch to dnsruby

**Comment by dentarg** [comment]
> I would go with addressable,

Actually, what I really would like is to be able pass in my own class. Like you can do with [excon](https://github.com/excon/excon#options):

```ruby
# use custom uri parser
require 'addressable/uri'
connection = Excon.new('http://geemus.com/', uri_parser: Addressable::URI)
```

The reason for this is because at [work](https://www.twingly.com/), we encounter a lot of bad input when we crawl the internet, so we have [wrapped addressable in our own gem](https://github.com/twingly/twingly-url), with a single purpose: do not raise any exception when parsing the URL.

**Comment by dentarg** [comment]
@alexdalitz also, not adding proper idn support, but catching the exception (if that could be done without any bad side effects) and re-raising a `Dnsruby` exception would be an improvement here

**Comment by alexdalitz** [comment]
OK, I'm afraid I've had almost zero spare time recently, so I've gone with the quickest solution and simply re-raised a Dnsruby exception here (as per your last suggestion). I hopeto add a punycode converter in a future release.

**Comment by alexdalitz** [comment]
Sorry about the delay.
Dnsruby now uses addressable to convert domain strings to punycode for IDNs. 
Thanks!
