### ISSUE TITLE
Need HMAC SHA512 TSIG keys support

### ISSUE THREAD

**Issue by adi-altiscale** [alexdalitz/dnsruby#97]
Can you please release a new gem version with the SHA512 support please. I see that the code is already checked in.

**Comment by alexdalitz** [comment]
Sure! I might just see if I can get puny code
Support as well but will try to make a release in the next week if that works for you?

Thanks,

Alex.

**Comment by adi-altiscale** [comment]
Thanks. That will work.

**Comment by alexdalitz** [comment]
Hi - 

FYI, I've just released dnsruby 1.59.1, primrarily for SHA512 support.

Please let me know of any problems.

Thanks,


Alex.

**Comment by adi-altiscale** [comment]
Thanks Alex
